
env:
  TERM: xterm-256color

window:
  decorations: full

  title: Terminal

  # Allow terminal applications to change Alacritty's window title.
  dynamic_title: true


scrolling:
  # Maximum number of lines in the scrollback buffer.
  # Specifying '0' will disable scrolling.
  history: 10000
  # Scrolling distance multiplier.
  multiplier: 3

font:
  # Normal (roman) font face
  normal:
    # Font family
    #
    # Default:
    #   - (macOS) Menlo
    #   - (Linux/BSD) monospace
    #   - (Windows) Consolas
    family: FiraCode Nerd Font #monospace

    # The `style` can be specified to pick a specific face.
    style: Regular

  # Bold font face
  bold:
    # Font family
    #
    # If the bold family is not specified, it will fall back to the
    # value specified for the normal font.
    family: FiraCode Nerd Font

    # The `style` can be specified to pick a specific face.
    style: Bold

  # Italic font face
  italic:
    # Font family
    #
    # If the italic family is not specified, it will fall back to the
    # value specified for the normal font.
    family: FantasqueSansMono Nerd Font Mono

    # The `style` can be specified to pick a specific face.
    style: Italic

  # Bold italic font face
  bold_italic:
    #Font family
    #
    # If the bold italic family is not specified, it will fall back to the
    # value specified for the normal font.
    family: FantasqueSansMono Nerd Font Mono

    # The `style` can be specified to pick a specific face.
    style: Bold Italic
# If `true`, bold text is drawn using the bright color variants.
#draw_bold_text_with_bright_colors: false
  # TokyoNight Alacritty Colors
# Kanagawa Alacritty Colors
colors:
  primary:
    background: '0x1f1f28'
    foreground: '0xdcd7ba'

  normal:
    black:   '0x090618'
    red:     '0xc34043'
    green:   '0x76946a'
    yellow:  '0xc0a36e'
    blue:    '0x7e9cd8'
    magenta: '0x957fb8'
    cyan:    '0x6a9589'
    white:   '0xc8c093'

  bright:
    black:   '0x727169'
    red:     '0xe82424'
    green:   '0x98bb6c'
    yellow:  '0xe6c384'
    blue:    '0x7fb4ca'
    magenta: '0x938aa9'
    cyan:    '0x7aa89f'
    white:   '0xdcd7ba'

  selection:
    background: '0x2d4f67'
    foreground: '0xc8c093'

  indexed_colors:
    - { index: 16, color: '0xffa066' }
    - { index: 17, color: '0xff5d62' }

