"$schema" = "https://starship.rs/config-schema.json"

# General settings
add_newline = false
command_timeout = 1000
format = "$all"

# Character settings
[character]
success_symbol = " [➜](fg:#7adba0 bold) "
error_symbol = "[✖](fg:#ff6b6b bold) "

# Azure configuration
[azure]
disabled = false
format = "on [$symbol($subscription)]($style) "
symbol = "󰠅 "
style = "blue bold"

# Google Cloud configuration
[gcloud]
format = "on [$symbol$account(@$domain)(\\($project\\))]($style) "

# Time configuration
[time]
disabled = false
format = "[\\[$time\\]]($style)"
style = "fg:#585858"
time_format = "%H:%M"

# Git settings
[git_branch]
symbol = " "
format = "[$symbol$branch(:$remote_branch)]($style) "
style = "fg:#7C6FFF bold"


[git_status]
format = "([$all_status$ahead_behind]($style))"
diverged = "<>⇡ ${ahead_count} ⇣ ${behind_count} "
conflicted = "[=${count}](fg:#ff6b6b bold) "
behind = "[⇣ ${count}](fg:#ff6b6b) "
ahead = "[⇡ ${count}](fg:#7C6FFF) "
modified = "[~${count}](fg:#ff6b6b bold)"
untracked = "[?${count}](fg:#89ddff)"
stashed = "[^${count}](fg:#ff79c6)"
staged = "[+${count}](fg:#50fa7b)"
deleted = "[x${count}](fg:#ff5555)"
renamed = "[»${count}](fg:#8be9fd)"
style = "fg:#ff6b6b"

# Status settings
[status]
disabled = false
format = "[$symbol $status]($style)"
symbol = ""
signal_symbol = ""
sigint_symbol = "𥉉"
not_found_symbol = ""
not_executable_symbol = ""

# Command duration settings
[cmd_duration]
disabled = false
min_time = 500                   # Show durations for commands >500ms
show_milliseconds = false
format = " [ $duration](grey) "

# Directory settings
[directory]
truncate_to_repo = false
truncation_length = 1
style = "fg:#7adba0"
read_only = " "
format = "[$path]($style)[$read_only]($read_only_style) "

# Language-specific settings
[c]
format = "[$symbol($version(-$name) )]($style)"
symbol = " "

[docker_context]
disabled = true
format = "[$symbol]($style) "
symbol = " "

[elixir]
format = "[$symbol($version \\(OTP $otp_version\\) )]($style)"
symbol = " "

[golang]
format = "[$symbol($version )]($style)"
symbol = " "

[nodejs]
format = "[$symbol($version )]($style)"
symbol = "󰎙 "

[python]
format = "[${symbol}${pyenv_prefix}(${version} )(\\($virtualenv\\) )]($style)"
symbol = " "

[rust]
format = "[$symbol($version)]($style)"
symbol = " "

[lua]
format = "[$symbol($version )]($style)"
symbol = " "

# Package manager settings
[package]
symbol = " "
style = "fg:#ffb86b"

# Terraform settings
[terraform]
format = "[$symbol$version]($style) "
symbol = "󱁢 "

# OS settings
[os]
disabled = false
format = "$symbol "
symbols = { Ubuntu = "", Macos = "", EndeavourOS = "", Arch = "" }

# Shell settings
[shell]
disabled = false
bash_indicator = ""
zsh_indicator = ""

# Jobs settings
[jobs]
symbol = " "
